[package]
name = "cix-cixfile"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
cix-common.workspace = true
cix-build.workspace = true
cix-index.workspace = true
cix-compose.workspace = true
libc.workspace = true
ignore.workspace = true
notify.workspace = true
ctrlc.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile = "3"
thiserror.workspace = true
similar.workspace = true

[dev-dependencies]
cix-run.workspace = true
