[package]
name = "cix"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cix-cixfile.workspace = true
cix-build.workspace = true
cix-common.workspace = true
cix-compose.workspace = true
cix-index.workspace = true
cix-run.workspace = true
anyhow.workspace = true
clap.workspace = true
ctrlc.workspace = true
ignore.workspace = true
notify.workspace = true
serde.workspace = true
serde_json.workspace = true
similar.workspace = true
tempfile.workspace = true

[dev-dependencies]
cix-test-support.workspace = true
libc.workspace = true
regex = "1"
tempfile = "3"
