[package]
name = "cix"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cix-cixfile.workspace = true
cix-import.workspace = true
cix-index.workspace = true
cix-run.workspace = true
anyhow.workspace = true
clap.workspace = true

[dev-dependencies]
regex = "1"
tempfile = "3"
