[package]
name = "cix"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cix-cixfile.workspace = true
cix-common.workspace = true
cix-compose.workspace = true
cix-index.workspace = true
cix-run.workspace = true
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true

[dev-dependencies]
libc.workspace = true
regex = "1"
tempfile = "3"
