[workspace]
resolver = "2"
members = [
  "crates/cix",
  "crates/cix-cixfile",
  "crates/cix-common",
  "crates/cix-compose",
  "crates/cix-index",
  "crates/cix-run",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
cix-common = { path = "crates/cix-common" }
cix-cixfile = { path = "crates/cix-cixfile" }
cix-compose = { path = "crates/cix-compose" }
cix-index = { path = "crates/cix-index" }
cix-run = { path = "crates/cix-run" }

anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_path_to_error = "0.1"
sha2 = "0.10"
thiserror = "2"
base64 = "0.22"
tiny_http = "0.12"
ureq = { version = "2", features = ["json"] }
libc = "0.2"
