daemon off;
pid /run/nginx/nginx.pid;
error_log stderr info;
events { }
http {
  access_log off;
  client_body_temp_path /var/cache/nginx/body;
  proxy_temp_path /var/cache/nginx/proxy;
  fastcgi_temp_path /var/cache/nginx/fastcgi;
  uwsgi_temp_path /var/cache/nginx/uwsgi;
  scgi_temp_path /var/cache/nginx/scgi;
  server {
    listen 127.0.0.1:34000;
    location = /api/v1/streaming/health {
      return 200 "OK\n";
    }
  }
}
