[package]
name = "cix-index"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cix-common.workspace = true
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
base64.workspace = true
tiny_http.workspace = true
ureq.workspace = true
libc.workspace = true
