[package]
name = "cix-run"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cix-common.workspace = true
cix-index.workspace = true
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
libc.workspace = true
tempfile = "3"

[dev-dependencies]
cix-test-support.workspace = true
